#!/usr/bin/env python3

import argparse
import subprocess
import os
import json
from time import time
from urllib.parse import urlparse

DEFAULT_LANGUAGE = "cpython"
DEFAULT_SUBMIT_TARGET = "main.py"
DEFAULT_WAIT_TIME = "0"
ATCODER_ROOT = "https://atcoder.jp/"
OJ_DOWNLOAD_HISTORY_DIR = os.path.join(os.environ["HOME"], ".cache/online-judge-tools/")
OJ_DOWNLOAD_HISTORY_NAME = "download-history.jsonl"
OJ_DOWNLOAD_HISTORY_PATH = os.path.join(OJ_DOWNLOAD_HISTORY_DIR, OJ_DOWNLOAD_HISTORY_NAME)

def get_args():
    parser = argparse.ArgumentParser(description="oj command wrapper for submit to AtCoder")
    parser.add_argument('-l', "--language", type=str, default=DEFAULT_LANGUAGE, help="submit language")
    parser.add_argument('-t', "--target", type=str, default=DEFAULT_SUBMIT_TARGET, help="target file for submit")
    parser.add_argument('-w', "--wait", type=str, default=DEFAULT_WAIT_TIME, help="wait time before submit")
    
    args = parser.parse_args()
    return args

def get_args_info():
    args = get_args()
    args_info = args.__dict__
    return args_info

def get_guessed_url():
    cwd = os.getcwd()
    
    parent_dir = os.path.split(cwd)[-1]
    if len(parent_dir) == 1:
        contest_alphabet = parent_dir
        contest_id = cwd.split("/")[-2]
        problem_id = "_".join([contest_id, contest_alphabet])
    else:
        contest_id = cwd.split("/")[-2]
        problem_id = parent_dir
    
    guessed_url = os.path.join(ATCODER_ROOT, "contests", contest_id, "tasks", problem_id)
    return guessed_url

def check_problem_url(url):
    command_elements = ["oj-api", "--wait", "0", "get-problem", url]
    command = " ".join(command_elements)
    response = subprocess.Popen(command, stdout=subprocess.PIPE, shell=True).communicate()[0]
    status = json.loads(response)["status"]
    
    if status == "ok": return True
    else: return False

def url_from_problem_id(problem_id):
    if problem_id.startswith("past"):
        contest = problem_id.split("_")[0]
        contest_id = contest + "-open"
    else:
        contest_id = problem_id.split("_")[0]
    guessed_url = os.path.join(ATCODER_ROOT, "contests", contest_id, "tasks", problem_id)
    return guessed_url

def url_input():
    input_info = input("input problem's URL or problem_id (ex. abc187_a)\ninput:")
    
    if urlparse(input_info).scheme != "":
        input_url = input_info
        print("input url: {}".format(input_url))
        return input_url
    
    else:
        problem_id = input_info
        guessed_url = url_from_problem_id(problem_id)
        print("guessed url: {}".format(guessed_url))
        return guessed_url
    
def write_dummy_history(problem_url):
    timestamp = int(time())
    directory = os.getcwd()
    dummy_history_dict = {"timestamp":timestamp, "directory":directory, "url":problem_url}
    dummy_history = json.dumps(dummy_history_dict) + "\n"
    
    if not os.path.isdir(OJ_DOWNLOAD_HISTORY_DIR):
        os.makedirs(OJ_DOWNLOAD_HISTORY_DIR)
    with open(OJ_DOWNLOAD_HISTORY_PATH, mode='a') as f:
        f.write(dummy_history)
    return

def get_problem_url():
    url = get_guessed_url()
    print("guessed url: \"{}\"".format(url))
    
    while check_problem_url(url) != True:
        print("Failure: \"{}\" is invalid URL".format(url))
        url = url_input()
    
    return url

def make_command():
    args_info = get_args_info()
    language = args_info["language"]
    submit_target = args_info["target"]

    url = get_problem_url()
    write_dummy_history(url)
    
    command_elements = ["oj", "s", url, submit_target]
    
    if language in ["cpython", "pypy"]:
        python_elements = ["--guess-python-interpreter", language]
        command_elements.extend(python_elements)
        
    wait_time = args_info["wait"]
    command_elements.extend(["--wait", wait_time])
    
    command = " ".join(command_elements)
    return command

def submit():
    command = make_command()
    subprocess.run(command, shell=True)

def main():
    submit()
    
if __name__ == "__main__":
    main()